# Default variables for SMTP Relay deployment
---
# Node.js Configuration
node_version: "20"
node_env: "production"

# Application Settings
app_name: smtp-relay
app_user: smtp-relay
app_dir: /opt/smtp-relay
config_dir: /etc/smtp-relay
log_dir: /var/log/smtp-relay

# Dashboard
dashboard_enabled: true

# Exchange Online Configuration
# IMPORTANT: Choose your API method!
# - graph_api: Recommended, no SMTP Auth needed
# - smtp_oauth2: Legacy, requires SMTP Auth
# - hybrid: Both with fallback
exchange_api_method: "graph_api"

# Auth method: device_code, client_credentials, or authorization_code
exchange_auth_method: "client_credentials"

# Azure AD Settings (override in host_vars or vault)
# exchange_tenant_id: "your-tenant-id"
# exchange_client_id: "your-client-id"
# exchange_client_secret: !vault |
#   $ANSIBLE_VAULT;1.1;AES256
#   ...

# Default sender email
# exchange_send_as: "relay@yourdomain.com"

# SMTP Ports Configuration
# Using ports > 1024 to avoid permission issues
smtp_port: 2525
smtp_submission_port: 2587
smtps_port: 2465
web_port: 3001

# IP Whitelist for no-auth access
smtp_ip_whitelist:
  - "192.168.0.0/16"
  - "10.0.0.0/8"
  - "172.16.0.0/12"

smtp_no_auth_networks:
  - "192.168.0.0/16"
  - "10.0.0.0/8"

# Allowed domains
allowed_sender_domains:
  - "*"  # Allow all internal senders

allowed_recipient_domains:
  - "*"  # Configure your domains here

# Rate Limiting
rate_limiting_enabled: true
max_messages_per_minute: 100
max_recipients_per_message: 100

# Queue Settings
queue_enabled: true
queue_retry_attempts: 3
queue_retry_delay: 300  # seconds
max_queue_size: 1000

# Monitoring
monitoring_enabled: true
monitoring_port: 8080

# Logging
log_level: "info"

# Security
force_https: false

# Redis (optional)
redis_host: "localhost"
redis_port: 6379

# Initial passwords (change these!)
admin_password: "Admin@2024!Secure"
helpdesk_password: "Helpdesk@2024!Secure"

# WebAuthn
rp_id: "{{ ansible_fqdn | default('localhost') }}"
origin: "http://{{ ansible_fqdn | default('localhost') }}:3001"