# Example Inventory for SMTP Relay
# Copy this to inventory/production/ and adjust for your environment

all:
  children:
    smtp_relay_servers:
      hosts:
        # Single server deployment
        relay1:
          ansible_host: 192.168.1.10  # Change to your server IP
          ansible_user: root
          
          # Azure AD Configuration (REQUIRED)
          exchange_tenant_id: "your-tenant-id"  # Or "common" for multi-tenant
          exchange_client_id: "your-application-id"
          
          # API Method Selection (choose one)
          # graph_api = Recommended, no SMTP Auth needed
          # smtp_oauth2 = Legacy, requires SMTP Auth enabled
          # hybrid = Both with fallback
          exchange_api_method: "graph_api"
          
          # Optional: Override default ports
          # smtp_port: 2525
          # smtp_submission_port: 2587
          # smtps_port: 2465
          
        # Multiple server deployment (optional)
        # relay2:
        #   ansible_host: 192.168.1.11
        #   ansible_user: root
        #   exchange_tenant_id: "your-tenant-id"
        #   exchange_client_id: "your-application-id"
        #   exchange_api_method: "graph_api"
      
      # Group variables for all relay servers
      vars:
        # Common settings for all hosts
        dashboard_enabled: true
        monitoring_enabled: true
        
        # IP Whitelist (adjust for your network)
        smtp_ip_whitelist:
          - "192.168.1.0/24"   # Local network
          - "10.0.0.0/8"       # Private network
          
        # Allowed domains
        allowed_recipient_domains:
          - "*"  # Allow all, or specify: ["yourdomain.com", "partner.com"]