---
- name: Deploy Legacy SMTP Relay
  hosts: smtp_relay_servers
  become: yes
  vars:
    app_name: smtp-relay
    app_user: smtp-relay
    app_dir: /opt/smtp-relay
    node_version: "20"
    config_dir: /etc/smtp-relay
    log_dir: /var/log/smtp-relay

  tasks:
    - name: Check Node.js version
      command: node --version
      register: node_installed
      ignore_errors: yes
      changed_when: false

    - name: Install Node.js repository (if needed)
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }}.x | bash -
      args:
        creates: /etc/yum.repos.d/nodesource*.repo
      when: 
        - node_installed.rc != 0 or (node_installed.stdout | regex_search('v(\d+)', '\\1') | first | int < 18)

    - name: Install required packages
      dnf:
        name:
          - nodejs
          - git
          - firewalld
        state: present

    - name: Create application user
      user:
        name: "{{ app_user }}"
        system: yes
        shell: /bin/false
        home: "{{ app_dir }}"
        create_home: no

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'
      loop:
        - "{{ app_dir }}"
        - "{{ config_dir }}"
        - "{{ log_dir }}"
        - "{{ app_dir }}/queue"
        - "{{ app_dir }}/certs"
        - "{{ app_dir }}/logs"
        - "{{ app_dir }}/.temp"

    - name: Clone/update repository
      git:
        repo: https://github.com/SilvioTormen/smtprelay.git
        dest: "{{ app_dir }}"
        version: main
        force: yes
      become_user: "{{ app_user }}"

    - name: Install Node.js dependencies (main)
      npm:
        path: "{{ app_dir }}"
        production: yes
      become_user: "{{ app_user }}"

    - name: Install Dashboard dependencies
      npm:
        path: "{{ app_dir }}/dashboard"
        production: yes
      become_user: "{{ app_user }}"
      when: dashboard_enabled | default(true)

    - name: Copy configuration file
      template:
        src: config.yml.j2
        dest: "{{ app_dir }}/config.yml"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0600'
      notify: restart smtp-relay

    - name: Generate .env file
      copy:
        content: |
          # Generated by Ansible
          NODE_ENV={{ node_env | default('production') }}
          JWT_SECRET={{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') | b64encode }}
          JWT_REFRESH_SECRET={{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') | b64encode }}
          SESSION_SECRET={{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') | b64encode }}
          ADMIN_INITIAL_PASSWORD={{ admin_password | default('Admin@2024!Secure') }}
          HELPDESK_INITIAL_PASSWORD={{ helpdesk_password | default('Helpdesk@2024!Secure') }}
          RP_ID={{ rp_id | default('localhost') }}
          ORIGIN={{ origin | default('http://localhost:3001') }}
          FORCE_HTTPS={{ force_https | default('false') }}
          TLS_CERT_PATH={{ app_dir }}/certs/cert.pem
          TLS_KEY_PATH={{ app_dir }}/certs/key.pem
          SMTP_PORT={{ smtp_port | default('2525') }}
          SMTP_SUBMISSION_PORT={{ smtp_submission_port | default('2587') }}
          SMTPS_PORT={{ smtps_port | default('2465') }}
          WEB_PORT={{ web_port | default('3001') }}
          REDIS_HOST={{ redis_host | default('localhost') }}
          REDIS_PORT={{ redis_port | default('6379') }}
          LOG_LEVEL={{ log_level | default('info') }}
          LOG_DIR={{ log_dir }}
        dest: "{{ app_dir }}/.env"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0600'
      notify: restart smtp-relay

    - name: Install systemd service
      copy:
        src: "{{ app_dir }}/smtp-relay.service"
        dest: /etc/systemd/system/smtp-relay.service
        remote_src: yes
      notify: reload systemd

    - name: Configure firewall for SMTP ports
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - "25"     # Legacy SMTP
        - "587"    # STARTTLS
        - "465"    # SMTPS
        - "2525"   # Alternative SMTP (no auth required)
        - "2587"   # Alternative submission
        - "2465"   # Alternative SMTPS
        - "3001"   # Web Dashboard

    - name: Configure firewall for monitoring
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - "8080"  # Health check
      when: enable_monitoring | default(true)

    - name: Set up log rotation
      copy:
        content: |
          {{ log_dir }}/*.log {
              daily
              rotate 30
              compress
              delaycompress
              missingok
              notifempty
              create 0644 {{ app_user }} {{ app_user }}
              sharedscripts
              postrotate
                  systemctl reload smtp-relay 2>/dev/null || true
              endscript
          }
        dest: /etc/logrotate.d/smtp-relay

    - name: Secure token file (if exists)
      file:
        path: "{{ app_dir }}/.tokens.json"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0600'
      ignore_errors: yes

    - name: Run post-install security script
      command: "{{ app_dir }}/scripts/post-install.sh"
      args:
        creates: "{{ app_dir }}/.post-install.done"
      environment:
        EUID: "0"

    - name: Mark post-install as done
      file:
        path: "{{ app_dir }}/.post-install.done"
        state: touch
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Enable and start service
      systemd:
        name: smtp-relay
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Enable and start dashboard service
      systemd:
        name: smtp-relay-dashboard
        enabled: yes
        state: started
        daemon_reload: yes
      when: dashboard_enabled | default(true)

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart smtp-relay
      systemd:
        name: smtp-relay
        state: restarted

---
# Inventory file example (inventory/hosts.yml):
# all:
#   children:
#     smtp_relay_servers:
#       hosts:
#         relay1:
#           ansible_host: 192.168.1.10
#           exchange_tenant_id: "your-tenant-id"
#           exchange_client_id: "your-client-id"
#           exchange_client_secret: !vault |
#             $ANSIBLE_VAULT;1.1;AES256
#             ...